// users
export const REQUEST_CURRENT_USER_SUCCESS = 'REQUEST_CURRENT_USER_SUCCESS';
export const REQUEST_CURRENT_USER_FAILURE = 'REQUEST_CURRENT_USER_FAILURE';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

// authentication
export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS';
export const REQUEST_LOGIN_FAILURE = 'REQUEST_LOGIN_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';

// topics
export const REQUEST_TOPIC_SUCCESS = 'REQUEST_TOPIC_SUCCESS';
export const REQUEST_TOPIC_FAILURE = 'REQUEST_TOPIC_FAILURE';
export const CREATE_TOPIC_SUCCESS = 'CREATE_TOPIC_SUCCESS';
export const CREATE_TOPIC_FAILURE = 'CREATE_TOPIC_FAILURE';

// subscriptions
export const REQUEST_SUBSCRIPTIONS_SUCCESS = 'REQUEST_SUBSCRIPTIONS_SUCCESS';
export const REQUEST_SUBSCRIPTIONS_FAILURE = 'REQUEST_SUBSCRIPTIONS_FAILURE';
export const CREATE_SUBSCRIPTION_SUCCESS = 'CREATE_SUBSCRIPTION_SUCCESS';
export const CREATE_SUBSCRIPTION_FAILURE = 'CREATE_SUBSCRIPTION_FAILURE';
export const DELETE_SUBSCRIPTION_SUCCESS = 'DELETE_SUBSCRIPTION_SUCCESS';
export const DELETE_SUBSCRIPTION_FAILURE = 'DELETE_SUBSCRIPTION_FAILURE';

// posts
export const REQUEST_POSTS_SUCCESS = 'REQUEST_POSTS_SUCCESS';
export const REQUEST_POSTS_FAILURE = 'REQUEST_POSTS_FAILURE';
export const CREATE_POSTS_SUCCESS = 'CREATE_POSTS_SUCCESS';
export const CREATE_POSTS_FAILURE = 'CREATE_POSTS_FAILURE';
