// users
export const REQUEST_CURRENT_USER_SUCCESS = 'REQUEST_CURRENT_USER_SUCCESS';
export const REQUEST_CURRENT_USER_FAILURE = 'REQUEST_CURRENT_USER_FAILURE';

// authentication
export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS';
export const REQUEST_LOGIN_FAILURE = 'REQUEST_LOGIN_FAILURE';

// topics
export const REQUEST_TOPIC_SUCCESS = 'REQUEST_TOPIC_SUCCESS';
export const REQUEST_TOPIC_FAILURE = 'REQUEST_TOPIC_FAILURE';

// subscriptions
export const REQUEST_SUBSCRIPTIONS_SUCCESS = 'REQUEST_SUBSCRIPTIONS_SUCCESS';
export const REQUEST_SUBSCRIPTIONS_FAILURE = 'REQUEST_SUBSCRIPTIONS_FAILURE';
export const CREATE_SUBSCRIPTION_SUCCESS = 'CREATE_SUBSCRIPTION_SUCCESS';
export const CREATE_SUBSCRIPTION_FAILURE = 'CREATE_SUBSCRIPTION_FAILURE';
export const DELETE_SUBSCRIPTION_SUCCESS = 'DELETE_SUBSCRIPTION_SUCCESS';
export const DELETE_SUBSCRIPTION_FAILURE = 'DELETE_SUBSCRIPTION_FAILURE';
